#%RAML 1.0 NamedExample
value:
  menuId: 101
  menuName: "BreakFastMenu" 
  restaurantId: 1
  links: 
  - linkName: "menuItems"
    href: "http://localhost:8081/restaurants/1/menus/101/menuItems"
  - linkName: "restaurant"
    href: "http://localhost:8081/restaurants/1/"