#%RAML 1.0 NamedExample
value:
  restaurantId: 1
  name: "Udupi Garden"
  address:     
    houseNumber: 202
    street: "Some Street"
    city: "Bangalore"
    pincode: 560066
  links: 
  - 
    linkName: "menus"
    href: "http://localhost:8081/restaurants/1/menus" 
  
  
  